name: loya
description: Loya - Premium Business Loyalty Platform
publish_to: 'none'
version: 1.0.30+3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.0
  firebase_messaging: ^15.1.7
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Navigation
  go_router: ^14.8.1
  
  # UI Components
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  fl_chart: ^0.70.2
  qr_flutter: ^4.1.0
  
  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.4
  flutter_secure_storage: ^9.2.4
  http: ^1.2.2
  image_picker: ^1.1.2
  
  # Phone Input
  intl_phone_field: ^3.2.0
  pinput: ^5.0.1
  
  # Payments (Tap)
  # tap_pay_sdk will be added when ready
  
  # Icons
  lucide_icons: ^0.257.0
  
  # Animations
  flutter_animate: ^4.5.2
  image_picker_for_web: ^3.1.1
  
  # QR Scanner
  mobile_scanner: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/


